export default function (nga, admin) {
    return nga.menu()
        .addChild(nga.menu()
            .title('Users')
            .icon('<span class="fa fa-users fa-fw"></span>')
            .addChild(nga.menu(admin.getEntity('users'))
                .title('Simple Users')
                .icon('<span class="fa fa-user fa-fw"></span>'))
        )
        // .addChild(nga.menu()
        //     .title('Submissions')
        //     .icon('<span class="fa fa-th-list fa-fw"></span>')
        //     .addChild(nga.menu(admin.getEntity('stickers'))
        //         .icon('<span class="fa fa-picture-o fa-fw"></span>'))
        //     .addChild(nga.menu(admin.getEntity('templates'))
        //         .icon('<span class="fa fa-camera fa-fw"></span>'))
        //     .addChild(nga.menu(admin.getEntity('tags'))
        //         .icon('<span class="fa fa-tags fa-fw"></span>'))
        //     .addChild(nga.menu(admin.getEntity('template_tags'))
        //         .icon('<span class="fa fa-tags fa-fw"></span>'))
        //     .addChild(nga.menu(admin.getEntity('actions'))
        //         .icon('<span class="fa fa-bolt ' +
        //             ' fa-fw"></span>'))
        //     .addChild(nga.menu(admin.getEntity('emotions'))
        //         .icon('<span class="fa fa-smile-o fa-fw"></span>'))
        // )
        // .addChild(nga.menu()
        //         .title('Statistics')
        //         .icon('<span class="fa fa-line-chart fa-fw"></span>')
        //     .addChild(nga.menu()
        //         .title('Stickers')
        //         .link('/statistics/sticker')
        //         .active(path => path == '/statistics/sticker')
        //         .icon('<span class="fa fa-scissors fa-fw"></span>'))
        // )
        // .addChild(nga.menu()
        //         .title('Gifs')
        //         .icon('<span class="fa fa-film fa-fw"></span>')
        //     .addChild(nga.menu(admin.getEntity('gifs'))
        //         .icon('<span class="fa fa-file-image-o fa-fw"></span>')
        //         .title('List'))
        //     .addChild(nga.menu(admin.getEntity('gif-tags'))
        //         .icon('<span class="fa fa-tags fa-fw"></span>')
        //         .title('Tags'))
        //     .addChild(nga.menu(nga.entity('gif-categories'))
        //         .icon('<span class="fa fa-tags fa-fw"></span>')
        //         .title('Categories') )
        // )
        // .addChild(nga.menu()
        //     .title('Images')
        //     .icon('<span class="fa fa-file-image-o fa-fw"></span>')
        //     .addChild(nga.menu()
        //         .title('Image Resize')
        //         .link('/image-resize')
        //         .active(path => path == '/image-resize')
        //         .icon('<span class="fa fa-picture-o fa-fw"></span>'))
        // );
}
